"""add survey columns and webinar settings

Revision ID: 28b9ed6fbfed
Revises: c340cf69e25f
Create Date: 2025-12-25 17:20:11.963934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b9ed6fbfed'
down_revision: Union[str, None] = 'c340cf69e25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinar_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webinar_datetime', sa.DateTime(), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('study_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age_range', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age_range')
    op.drop_column('users', 'study_status')
    op.drop_table('webinar_settings')
    # ### end Alembic commands ###
