"""add_phone_number_2

Revision ID: 48e50fba71c5
Revises: 28b9ed6fbfed
Create Date: 2025-12-25 15:43:20.279493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e50fba71c5'
down_revision: Union[str, None] = '28b9ed6fbfed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number_2')
    # ### end Alembic commands ###
