"""add_user_details

Revision ID: 52c771ba90df
Revises: 652951b3384d
Create Date: 2025-12-25 12:20:31.780096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c771ba90df'
down_revision: Union[str, None] = '652951b3384d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
