"""add_webinar_link

Revision ID: a82b6c7d9e1f
Revises: e537b5468339
Create Date: 2025-12-26 17:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82b6c7d9e1f'
down_revision: Union[str, None] = 'e537b5468339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_settings', sa.Column('webinar_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webinar_settings', 'webinar_link')
    # ### end Alembic commands ###
