"""update_webinar_reminders

Revision ID: e537b5468339
Revises: 48e50fba71c5
Create Date: 2025-12-26 16:24:49.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e537b5468339'
down_revision: Union[str, None] = '48e50fba71c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_settings', sa.Column('sent_1h', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('webinar_settings', sa.Column('sent_30m', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('webinar_settings', sa.Column('sent_15m', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('webinar_settings', sa.Column('sent_5m', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('webinar_settings', sa.Column('sent_start', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_column('webinar_settings', 'reminder_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webinar_settings', sa.Column('reminder_sent', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default='false'))
    op.drop_column('webinar_settings', 'sent_start')
    op.drop_column('webinar_settings', 'sent_5m')
    op.drop_column('webinar_settings', 'sent_15m')
    op.drop_column('webinar_settings', 'sent_30m')
    op.drop_column('webinar_settings', 'sent_1h')
    # ### end Alembic commands ###
